name: Create issues for duplicates

on:
  workflow_call:
    inputs:
      create_issue:
        type: boolean
        required: false
        default: false

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    name: Check if duplicates exists.
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NIXPKGS_TOKEN }}
          ref: ${{ github.head_ref }}
      - run: |
          echo "Input: ${{ inputs.create_issue }}"
          if ${{ inputs.creat_issue }}
          then
            ./bin/check-duplicates.sh
          else
            ./bin/check-duplicates.sh "check_only"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
