name: Check if duplicates exists

on:
  push:
    paths:
      - manifest.txt
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-new-plugins:
    runs-on: ubuntu-latest
    name: Check if duplicates exists. (Does nothing about it for now)
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NIXPKGS_TOKEN }}
          ref: ${{ github.head_ref }}
      - run: |
          ./bin/check-duplicates.sh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
