name: Check if duplicates exists, and creates an issue if it finds some

on:
  push:
    paths:
      - manifest.txt
    branches:
      - main
  workflow_dispatch:

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    name: Check if duplicates exists.
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NIXPKGS_TOKEN }}
          ref: ${{ github.head_ref }}
      - run: |
          ./bin/check-duplicates.sh
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
